name: CI

on: [push]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag davinci-api:$(date +%s)
    - name: Test
      run: nose2 --config test/nose2.cfg --with-cov --coverage-report xml --coverage-config test/coverage/.coveragerc
