name: CI

on: 
  push:
    refs/heads:
      - master
      - staging
      - developement
      - contrib

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -Iv pandas==0.23.3 flask-restful==0.3.6 requests==2.21.0 PyYAML==5.1 Babel==2.6.0 impyla==0.15a1 sklearn==0.0
    - name: Linting (pylint)
      run: |
        pip install -Iv pylint==2.4.4
        ls -l
        ls -l ./reports/pylint.txt
        sudo pylint ./app/**/*.py --msg-template="{path}:{line}: [{msg_id}({symbol}), {obj}] {msg}" --reports=n --output-format=parseable >> ./reports/pylint.txt
    - name: Linting (flake8)
      run: |
        pip install -Iv flake8==3.7.9
        flake8 . --format='%(path)s:%(row)s: [%(code)s({symbol}), {obj}] %(text)s' --exit-zero --output-file=./reports/flake8.txt
    - name: Unit testing
      run: |
        pip install -Iv nose2==0.9.1
        nose2 --config app/test/nose2.cfg --with-cov --coverage-report xml --coverage-config app/test/coverage/.coveragerc
    - name: SonarCloud Scan
      uses: sonarsource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
