name: CI

on: [push]

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -Iv nose==1.3.7
    - uses: actions/checkout@master
    - name: Test
      run: nose2 --config test/nose2.cfg --with-cov --coverage-report xml --coverage-config test/coverage/.coveragerc
